version: '3.1'

services:
  db:
    image: postgres:16.2-alpine
    container_name: db_postgree
    restart: always
    environment:
      POSTGRES_DB: shorturl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5435:5432  